from PIL import Image, ImageDraw, ImageFont
import os

def generate_text_image(text, font_path, output_path, size=(300, 100)):
    img = Image.new('L', size, color=255)
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(font_path, 32)
    draw.text((10, 30), text, font=font, fill=0)
    img.save(output_path)

# Directories
os.makedirs("dataset/english", exist_ok=True)
os.makedirs("dataset/urdu", exist_ok=True)

# Fonts
english_font = "arial.ttf"
urdu_font = r"D:\PythonProjects\Image Classification\NotoNastaliqUrdu-VariableFont_wght.ttf"  # You can download from Google Fonts

# Sample texts
english_samples = [
    "Hello", "Welcome", "This is a test", "OpenAI", "Text Image", "Good morning", "Good afternoon", "Good evening", "Good night", "How are you?",
    "I'm fine, thank you", "What's your name?", "My name is John", "Nice to meet you", "See you later", "Goodbye", "Please", "Thank you", "You're welcome", "Excuse me",
    "I'm sorry", "Yes", "No", "Maybe", "Please repeat", "I don't understand", "Can you help me?", "Where is the restroom?", "How much is this?", "I need help",
    "Can I have the menu?", "I'd like to order", "Water, please", "Coffee, please", "Tea, please", "Milk, please", "Sugar, please", "Salt, please", "Pepper, please", "Bread, please",
    "Meat", "Chicken", "Fish", "Vegetables", "Fruit", "Dessert", "Breakfast", "Lunch", "Dinner", "Snack",
    "Today", "Tomorrow", "Yesterday", "Now", "Later", "Morning", "Afternoon", "Evening", "Night", "Day",
    "Week", "Month", "Year", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    "Red", "Blue", "Green", "Yellow", "Black", "White", "Orange", "Purple", "Brown", "Pink",
    "Big", "Small", "Hot", "Cold", "Good", "Bad", "Happy", "Sad", "New", "Old",
    "Fast", "Slow", "High", "Low", "Near", "Far", "Open", "Closed", "Left", "Right",
    "Up", "Down", "Inside", "Outside", "Here", "There", "Who", "What", "When", "Where",
    "Why", "How", "Many", "Much", "Few", "Little", "All", "None", "Some", "Any",
    "And", "Or", "But", "If", "Because", "So", "Then", "Before", "After", "While",
    "Always", "Never", "Often", "Sometimes", "Seldom", "Usually", "Rarely", "Frequently", "Mostly", "Ever",
    "Home", "Work", "School", "Hospital", "Police station", "Fire station", "Airport", "Train station", "Bus station", "Hotel",
    "Restaurant", "Cafe", "Shop", "Market", "Bank", "Post office", "Library", "Museum", "Park", "Beach",
    "Mountain", "River", "Lake", "Ocean", "Forest", "Desert", "City", "Town", "Village", "Street",
    "Road", "Bridge", "Building", "House", "Apartment", "Room", "Door", "Window", "Table", "Chair",
    "Bed", "Sofa", "Lamp", "Book", "Pen", "Paper", "Computer", "Phone", "Television", "Radio",
    "Car", "Bicycle", "Motorcycle", "Truck", "Bus", "Train", "Plane", "Boat", "Ship", "Taxi",
    "Driver", "Passenger", "Pilot", "Doctor", "Nurse", "Teacher", "Student", "Engineer", "Artist", "Writer",
    "Musician", "Dancer", "Singer", "Actor", "Athlete", "Scientist", "Researcher", "Programmer", "Developer", "Designer",
    "Manager", "Employee", "Boss", "Colleague", "Friend", "Family", "Mother", "Father", "Brother", "Sister",
    "Son", "Daughter", "Husband", "Wife", "Grandfather", "Grandmother", "Grandson", "Granddaughter", "Uncle", "Aunt",
    "Cousin", "Nephew", "Niece", "Child", "Adult", "Man", "Woman", "Boy", "Girl", "Baby",
    "People", "Person", "Life", "Death", "Love", "Hate", "Joy", "Sorrow", "Peace", "War",
    "Money", "Time", "World", "Country", "City", "Village", "Nature", "Animal", "Plant", "Flower",
    "Tree", "Food", "Drink", "Music", "Art", "Sport", "Game", "Book", "Movie", "Show",
    "News", "Weather", "Information", "Question", "Answer", "Problem", "Solution", "Idea", "Opinion", "Fact",
    "Truth", "Lie", "Dream", "Reality", "Hope", "Fear", "Courage", "Brave", "Strong", "Weak",
    "Rich", "Poor", "Clean", "Dirty", "Empty", "Full", "Light", "Dark", "Loud", "Quiet",
    "Soft", "Hard", "Smooth", "Rough", "Wet", "Dry", "Heavy", "Light (weight)", "Long", "Short",
    "Wide", "Narrow", "Deep", "Shallow", "Thick", "Thin", "Warm", "Cool", "Bright", "Dim",
    "Simple", "Complex", "Easy", "Difficult", "Important", "Unimportant", "Necessary", "Unnecessary", "Possible", "Impossible",
    "Probable", "Improbable", "Certain", "Uncertain", "Known", "Unknown", "Visible", "Invisible", "Audible", "Inaudible",
    "Beautiful", "Ugly", "Handsome", "Pretty", "Charming", "Elegant", "Graceful", "Attractive", "Repulsive", "Disgusting",
    "Delicious", "Tasteless", "Sweet", "Sour", "Bitter", "Spicy", "Salty", "Fresh", "Stale", "Rotten",
    "Early", "Late", "Punctual", "Delay", "Hurry", "Rush", "Wait", "Start", "Finish", "Begin",
    "End", "Continue", "Stop", "Pause", "Resume", "Repeat", "Change", "Improve", "Worsen", "Develop",
    "Grow", "Shrink", "Expand", "Contract", "Increase", "Decrease", "Rise", "Fall", "Go", "Come",
    "Walk", "Run", "Jump", "Swim", "Fly", "Drive", "Ride", "Talk", "Speak", "Listen",
    "Hear", "See", "Look", "Watch", "Read", "Write", "Learn", "Teach", "Study", "Practice",
    "Work", "Play", "Eat", "Drink", "Sleep", "Wake up", "Get up", "Sit down", "Stand up", "Lie down",
    "Open", "Close", "Push", "Pull", "Cut", "Tear", "Break", "Fix", "Repair", "Build",
    "Destroy", "Create", "Invent", "Discover", "Explore", "Travel", "Visit", "Live", "Die", "Be",
    "Have", "Do", "Make", "Get", "Give", "Take", "Bring", "Send", "Receive", "Buy",
    "Sell", "Pay", "Cost", "Win", "Lose", "Find", "Lose (misplace)", "Search", "Find (discover)", "Catch",
    "Throw", "Hold", "Drop", "Lift", "Carry", "Wear", "Put on", "Take off", "Wash", "Clean",
    "Cook", "Bake", "Fry", "Boil", "Roast", "Grill", "Chop", "Slice", "Mix", "Stir",
    "Pour", "Serve", "Eat", "Drink", "Taste", "Smell", "Touch", "Feel", "Hear", "See",
    "Think", "Know", "Understand", "Believe", "Doubt", "Remember", "Forget", "Imagine", "Dream", "Hope",
    "Wish", "Want", "Need", "Like", "Dislike", "Love", "Hate", "Enjoy", "Prefer", "Accept",
    "Refuse", "Agree", "Disagree", "Allow", "Forbid", "Permit", "Prohibit", "Request", "Order", "Command",
    "Suggest", "Recommend", "Advise", "Warn", "Threaten", "Promise", "Apologize", "Forgive", "Thank", "Congratulate",
    "Celebrate", "Attend", "Participate", "Join", "Leave", "Arrive", "Depart", "Enter", "Exit", "Follow",
    "Lead", "Guide", "Help", "Assist", "Support", "Oppose", "Resist", "Fight", "Defend", "Attack",
    "Protect", "Guard", "Hide", "Show", "Display", "Reveal", "Conceal", "Explain", "Describe", "Tell",
    "Ask", "Answer", "Reply", "Respond", "Communicate", "Discuss", "Debate", "Argue", "Convince", "Persuade",
    "Influence", "Control", "Manage", "Organize", "Plan", "Prepare", "Execute", "Implement", "Achieve", "Succeed",
    "Fail", "Improve", "Worsen", "Progress", "Regress", "Advance", "Retreat", "Forward", "Backward", "Across",
    "Through", "Around", "About", "Under", "Over", "Between", "Among", "Next to", "Beside", "In front of",
    "Behind", "Above", "Below", "On", "In", "At", "From", "To", "With", "Without",
    "For", "Of", "By", "As", "Than", "From", "Into", "Onto", "Out of", "Toward",
    "Against", "Before", "After", "During", "Until", "Since", "While", "Though", "Although", "Even if",
    "Unless", "Provided that", "So that", "In order to", "Despite", "In spite of", "Instead of", "Because of", "Due to", "Thanks to",
    "According to", "On behalf of", "In addition to", "Apart from", "Except for", "Excluding", "Including", "Regarding", "Concerning", "About",
    "Plus", "Minus", "Times", "Divided by", "Equal to", "Greater than", "Less than", "Percent", "Number", "Amount",
    "Quantity", "Measure", "Weight", "Length", "Width", "Height", "Depth", "Area", "Volume", "Speed",
    "Temperature", "Pressure", "Energy", "Power", "Force", "Light (illumination)", "Sound", "Noise", "Silence", "Vibration",
    "Wave", "Particle", "Element", "Compound", "Mixture", "Solution", "Gas", "Liquid", "Solid", "Plasma",
    "Atom", "Molecule", "Cell", "Tissue", "Organ", "System", "Organism", "Species", "Population", "Community",
    "Ecosystem", "Environment", "Climate", "Weather", "Season", "Spring", "Summer", "Autumn", "Winter", "Rain",
    "Snow", "Wind", "Cloud", "Fog", "Sun", "Moon", "Star", "Planet", "Galaxy", "Universe",
    "Space", "Time", "Dimension", "Gravity", "Magnetism", "Electricity", "Heat", "Cold", "Light (spectrum)", "Sound (frequency)",
    "Color", "Shape", "Size", "Texture", "Pattern", "Form", "Structure", "Function", "Purpose", "Reason",
    "Cause", "Effect", "Result", "Consequence", "Source", "Origin", "Destination", "Journey", "Route", "Path",
    "Direction", "Location", "Position", "Place", "Point", "Line", "Curve", "Angle", "Circle", "Square",
    "Triangle", "Rectangle", "Oval", "Sphere", "Cube", "Cylinder", "Cone", "Pyramid", "Spiral", "Helix",
    "Network", "System", "Process", "Procedure", "Method", "Technique", "Strategy", "Tactic", "Plan", "Scheme",
    "Program", "Application", "Software", "Hardware", "Data", "Information", "Knowledge", "Wisdom", "Intelligence", "Creativity",
    "Imagination", "Memory", "Thought", "Emotion", "Feeling", "Sensation", "Perception", "Consciousness", "Mind", "Spirit",
    "Soul", "Body", "Health", "Sickness", "Pain", "Pleasure", "Comfort", "Discomfort", "Hunger", "Thirst",
    "Fatigue", "Energy", "Strength", "Weakness", "Balance", "Imbalance", "Harmony", "Conflict", "Order", "Chaos",
    "Justice", "Injustice", "Right", "Wrong", "Goodness", "Evil", "Virtue", "Vice", "Moral", "Ethical",
    "Legal", "Illegal", "Law", "Rule", "Regulation", "Principle", "Value", "Belief", "Faith", "Religion",
    "Spirituality", "Culture", "Tradition", "Custom", "Ritual", "Ceremony", "Celebration", "Festival", "Holiday", "Event",
    "Meeting", "Appointment", "Schedule", "Deadline", "Task", "Project", "Goal", "Objective", "Aim", "Purpose",
    "Meaning", "Significance", "Importance", "Value", "Worth", "Price", "Cost", "Budget", "Finance", "Economy",
    "Business", "Trade", "Commerce", "Industry", "Agriculture", "Technology", "Science", "Research", "Education", "Learning",
    "Teaching", "Training", "Development", "Growth", "Progress", "Innovation", "Discovery", "Invention", "Exploration", "Adventure",
    "Journey", "Travel", "Vacation", "Holiday", "Leisure", "Hobby", "Sport", "Game", "Art", "Music",
    "Dance", "Theater", "Cinema", "Television", "Radio", "Internet", "Website", "Email", "Message", "Call",
    "Phone", "Computer", "Laptop", "Tablet", "Smartphone", "Camera", "Microphone", "Speaker", "Headphones", "Printer",
    "Scanner", "Keyboard", "Mouse", "Screen", "Monitor", "Display", "Network", "Connection", "Wireless", "Bluetooth",
    "Cable", "Plug", "Socket", "Battery", "Charger", "Power", "Electricity", "Light", "Darkness", "Shadow",
    "Reflection", "Mirror", "Lens", "Glass", "Plastic", "Metal", "Wood", "Stone", "Concrete", "Brick",
    "Fabric", "Leather", "Paper", "Ink", "Paint", "Brush", "Pencil", "Eraser", "Ruler", "Scissors",
    "Glue", "Tape", "Nail", "Screw", "Hammer", "Wrench", "Screwdriver", "Drill", "Saw", "Axe",
    "Knife", "Fork", "Spoon", "Plate", "Bowl", "Cup", "Glass", "Bottle", "Can", "Jar",
    "Bag", "Box", "Container", "Basket", "Shelf", "Drawer", "Cabinet", "Closet", "Wardrobe", "Hanger",
    "Clothes", "Shirt", "T-shirt", "Jacket", "Coat", "Sweater", "Pants", "Jeans", "Shorts", "Skirt",
    "Dress", "Socks", "Shoes", "Boots", "Sandals", "Hat", "Cap", "Gloves", "Scarf", "Belt",
    "Tie", "Jewelry", "Ring", "Necklace", "Bracelet", "Earrings", "Watch", "Glasses", "Sunglasses", "Umbrella",
    "Key", "Lock", "Wallet", "Purse", "Backpack", "Suitcase", "Luggage", "Ticket", "Passport", "Map",
    "Compass", "Globe", "Flag", "Anthem", "Symbol", "Emblem", "Logo", "Brand", "Company", "Corporation",
    "Organization", "Institution", "Government", "Politics", "Law", "Justice", "Crime", "Punishment", "Prison", "Court",
    "Judge", "Lawyer", "Police", "Soldier", "Army", "Navy", "Air force", "Military", "War", "Peace",
    "Treaty", "Agreement", "Contract", "Promise", "Oath", "Pledge", "Commitment", "Responsibility", "Duty", "Obligation",
    "Right", "Privilege", "Freedom", "Liberty", "Equality", "Justice", "Fairness", "Honesty", "Integrity", "Trust",
    "Loyalty", "Respect", "Kindness", "Generosity", "Compassion", "Empathy", "Patience", "Tolerance", "Courage", "Bravery",
    "Strength", "Resilience", "Determination", "Perseverance", "Ambition", "Motivation", "Inspiration", "Creativity", "Innovation", "Discovery",
    "Research", "Experiment", "Theory", "Hypothesis", "Conclusion", "Evidence", "Fact", "Data", "Analysis", "Synthesis",
    "Abstract", "Concrete", "Concept", "Idea", "Thought", "Opinion", "Belief", "View", "Perspective", "Point of view",
    "Assumption", "Presumption", "Inference", "Deduction", "Induction", "Logic", "Reasoning", "Argument", "Debate", "Discussion",
    "Conversation", "Dialogue", "Speech", "Presentation", "Lecture", "Seminar", "Workshop", "Conference", "Meeting", "Interview",
    "Survey", "Questionnaire", "Report", "Document", "File", "Folder", "Cabinet", "Shelf", "Desk", "Chair",
    "Table", "Lamp", "Clock", "Calendar", "Book", "Magazine", "Newspaper", "Letter", "Envelope", "Stamp",
    "Postcard", "Greeting card", "Invitation", "Ticket", "Receipt", "Invoice", "Bill", "Contract", "Form", "Application",
    "Resume", "Curriculum vitae", "Certificate", "Diploma", "Degree", "Award", "Medal", "Trophy", "Prize", "Gift",
    "Present", "Souvenir", "Memento", "Keepsake", "Collection", "Hobby", "Game", "Puzzle", "Toy", "Doll",
    "Action figure", "Board game", "Card game", "Video game", "Console", "Controller", "Joystick", "Screen", "Monitor", "Display",
    "Speaker", "Headphones", "Microphone", "Camera", "Webcam", "Printer", "Scanner", "Keyboard", "Mouse", "USB drive",
    "Hard drive", "Solid state drive", "Memory card", "Router", "Modem", "Server", "Network", "Internet", "Website", "Blog",
    "Forum", "Social media", "Email", "Chat", "Message", "Call", "Video call", "Conference call", "Voicemail", "Text message",
    "Notification", "Alert", "Warning", "Error", "Bug", "Glitch", "Crash", "Restart", "Update", "Upgrade",
    "Install", "Uninstall", "Download", "Upload", "Save", "Open", "Close", "Copy", "Paste", "Cut",
    "Delete", "Undo", "Redo", "Print", "Scan", "Search", "Find", "Replace", "Select", "Deselect",
    "Click", "Double click", "Right click", "Drag", "Drop", "Scroll", "Zoom in", "Zoom out", "Maximize", "Minimize",
    "Restore", "Refresh", "Load", "Save as", "New folder", "Rename", "Properties", "Settings", "Options", "Preferences",
    "Help", "About", "Exit", "Quit"
]

urdu_samples = [
    "سلام", "خوش آمدید", "یہ ایک آزمائش ہے", "اوپن اے آئی", "متن کی تصویر", "صبح بخیر", "دوپہر بخیر", "شام بخیر", "شب بخیر", "آپ کیسے ہیں؟",
    "میں ٹھیک ہوں، شکریہ", "آپ کا نام کیا ہے؟", "میرا نام جان ہے", "آپ سے مل کر خوشی ہوئی", "پھر ملیں گے", "خدا حافظ", "مہربانی", "شکریہ", "خوش آمدید", "معاف کیجئے",
    "میں معذرت خواہ ہوں", "جی ہاں", "نہیں", "شاید", "دوبارہ کہیے", "میں سمجھا نہیں", "کیا آپ میری مدد کر سکتے ہیں؟", "واش روم کہاں ہے؟", "یہ کتنے کا ہے؟", "مجھے مدد کی ضرورت ہے",
    "کیا مجھے مینیو مل سکتا ہے؟", "میں آرڈر کرنا چاہوں گا", "پانی، براہ مہربانی", "کافی، براہ مہربانی", "چائے، براہ مہربانی", "دودھ، براہ مہربانی", "چینی، براہ مہربانی", "نمک، براہ مہربانی", "کالی مرچ، براہ مہربانی", "روٹی، براہ مہربانی",
    "گوشت", "مرغی", "مچھلی", "سبزیاں", "پھل", "میٹھا", "ناشتہ", "دوپہر کا کھانا", "رات کا کھانا", "ہلکا پھلکا",
    "آج", "کل (آنے والا)", "کل (گزرا ہوا)", "ابھی", "بعد میں", "صبح", "دوپہر", "شام", "رات", "دن",
    "ہفتہ", "مہینہ", "سال", "پیر", "منگل", "بدھ", "جمعرات", "جمعہ", "ہفتہ", "اتوار",
    "سرخ", "نیلا", "سبز", "پیلا", "سیاہ", "سفید", "نارنجی", "جامنی", "بھورا", "گلابی",
    "بڑا", "چھوٹا", "گرم", "ٹھنڈا", "اچھا", "برا", "خوش", "غمگین", "نیا", "پرانا",
    "تیز", "آہستہ", "اونچا", "نیچا", "قریب", "دور", "کھلا", "بند", "بایاں", "دایاں",
    "اوپر", "نیچے", "اندر", "باہر", "یہاں", "وہاں", "کون", "کیا", "کب", "کہاں",
    "کیوں", "کیسے", "کئی", "بہت", "چند", "تھوڑا", "سب", "کوئی نہیں", "کچھ", "کوئی",
    "اور", "یا", "لیکن", "اگر", "کیونکہ", "اس لیے", "پھر", "پہلے", "بعد", "جبکہ",
    "ہمیشہ", "کبھی نہیں", "اکثر", "کبھی کبھار", "شاذ و نادر", "عام طور پر", "کم ہی", "بار بار", "زیادہ تر", "کبھی",
    "گھر", "کام", "اسکول", "اسپتال", "پولیس اسٹیشن", "فائر اسٹیشن", "ہوائی اڈہ", "ریلوے اسٹیشن", "بس اسٹیشن", "ہوٹل",
    "ریستوراں", "کیفے", "دکان", "بازار", "بینک", "ڈاکخانہ", "لائبریری", "عجائب گھر", "پارک", "ساحل",
    "پہاڑ", "دریا", "جھیل", "سمندر", "جنگل", "صحرا", "شہر", "قصبہ", "گاؤں", "گلی",
    "سڑک", "پل", "عمارت", "گھر", "اپارٹمنٹ", "کمرہ", "دروازہ", "کھڑکی", "میز", "کرسی",
    "بستر", "صوفہ", "لیمپ", "کتاب", "قلم", "کاغذ", "کمپیوٹر", "فون", "ٹیلی ویژن", "ریڈیو",
    "گاڑی", "سائیکل", "موٹر سائیکل", "ٹرک", "بس", "ٹرین", "ہوائی جہاز", "کشتی", "جہاز", "ٹیکسی",
    "ڈرائیور", "مسافر", "پائلٹ", "ڈاکٹر", "نرس", "استاد", "طالب علم", "انجینئر", "مصور", "مصنف",
    "موسیقار", "رقاص", "گلوکار", "اداکار", "کھلاڑی", "سائنسدان", "محقق", "پروگرامر", "ڈویلپر", "ڈیزائنر",
    "منیجر", "ملازم", "مالک", "ساتھی", "دوست", "خاندان", "ماں", "باپ", "بھائی", "بہن",
    "بیٹا", "بیٹی", "شوہر", "بیوی", "دادا", "دادی", "پوتا", "پوتی", "چچا", "پھوپھی",
    "کزن", "بھتیجا", "بھتیجی", "بچہ", "بالغ", "مرد", "عورت", "لڑکا", "لڑکی", "نوزائیدہ",
    "لوگ", "شخص", "زندگی", "موت", "محبت", "نفرت", "خوشی", "غم", "امن", "جنگ",
    "پیسہ", "وقت", "دنیا", "ملک", "شہر", "گاؤں", "فطرت", "جانور", "پودا", "پھول",
    "درخت", "کھانا", "پینا", "موسیقی", "فنون", "کھیل", "گیم", "کتاب", "فلم", "شو",
    "خبریں", "موسم", "معلومات", "سوال", "جواب", "مسئلہ", "حل", "خیال", "رائے", "حقیقت",
    "سچ", "جھوٹ", "خواب", "حقیقت", "امید", "خوف", "ہمت", "بہادر", "مضبوط", "کمزور",
    "امیر", "غریب", "صاف", "گندا", "خالی", "بھرا ہوا", "روشن", "اندھیرا", "اونچی آواز", "خاموش",
    "نرم", "سخت", "ہموار", "کھردرا", "گیلا", "خشک", "بھاری", "ہلکا (وزن)", "لمبا", "چھوٹا",
    "چوڑا", "تنگ", "گہرا", "اتلا", "موٹا", "پتلا", "گرم", "ٹھنڈا", "چمکدار", "مدھم",
    "آسان", "پیچیدہ", "آسان", "مشکل", "اہم", "غیر اہم", "ضروری", "غیر ضروری", "ممکن", "ناممکن",
    "ممکن", "ناممکن", "یقینی", "غیر یقینی", "معلوم", "نامعلوم", "دیکھنے کے قابل", "غیر مرئی", "سننے کے قابل", "غیر قابل سماعت",
    "خوبصورت", "بدصورت", "خوبصورت", "پیاری", "دلکش", "خوبصورت", "باکمال", "دلکش", "مکروہ", "گھناؤنا",
    "مزیدار", "بے ذائقہ", "میٹھا", "کھٹا", "کڑوا", "مسالہ دار", "نمکین", "تازہ", "باسی", "گلا ہوا",
    "جلدی", "دیر", "وقت کا پابند", "تاخیر", "جلدی کرو", "جلدی", "انتظار", "شروع کریں", "ختم کریں", "شروع کریں",
    "ختم", "جاری رکھیں", "روکیں", "وقفہ", "دوبارہ شروع کریں", "دوبارہ", "تبدیل کریں", "بہتر بنائیں", "بدتر کریں", "ترقی کریں",
    "بڑھنا", "سکڑنا", "پھیلانا", "سکڑنا", "بڑھانا", "کم کرنا", "اٹھنا", "گرنا", "جانا", "آنا",
    "چلنا", "دوڑنا", "چھلانگ لگانا", "تیرنا", "اڑنا", "گاڑی چلانا", "سواری کرنا", "بات کرنا", "بولنا", "سننا",
    "سننا", "دیکھنا", "دیکھنا", "دیکھنا", "پڑھنا", "لکھنا", "سیکھنا", "سکھانا", "مطالعہ کرنا", "مشق کرنا",
    "کام کرنا", "کھیلنا", "کھانا", "پینا", "سونا", "جاگنا", "اٹھنا", "بیٹھنا", "کھڑا ہونا", "لیٹنا",
    "کھولنا", "بند کرنا", "دھکیلنا", "کھینچنا", "کاٹنا", "پھاڑنا", "توڑنا", "ٹھیک کرنا", "مرمت کرنا", "بنانا",
    "تباہ کرنا", "تخلیق کرنا", "ایجاد کرنا", "دریافت کرنا", "دریافت کرنا", "سفر کرنا", "دورہ کرنا", "رہنا", "مرنا", "ہونا",
    "ہونا", "کرنا", "بنانا", "حاصل کرنا", "دینا", "لینا", "لانا", "بھیجنا", "وصول کرنا", "خریدنا",
    "بیچنا", "ادائیگی کرنا", "لاگت", "جیتنا", "ہارنا", "تلاش کرنا", "گم کرنا", "تلاش کرنا", "تلاش کرنا", "پکڑنا",
    "پھینکنا", "پکڑنا", "گرانا", "اٹھانا", "لے جانا", "پہننا", "پہننا", "اتارنا", "دھونا", "صاف کرنا",
    "پکانا", "بیک کرنا", "تلنا", "ابالنا", "بھوننا", "گرل کرنا", "کاٹنا", "ٹکڑے کرنا", "ملانا", "ہلانا",
    "ڈالنا", "پیش کرنا", "کھانا", "پینا", "چکھنا", "سونگھنا", "چھونا", "محسوس کرنا", "سننا", "دیکھنا",
    "سوچنا", "جاننا", "سمجھنا", "یقین کرنا", "شک کرنا", "یاد رکھنا", "بھول جانا", "تصور کرنا", "خواب دیکھنا", "امید کرنا",
    "خواہش کرنا", "چاہنا", "ضرورت", "پسند کرنا", "ناپسند کرنا", "محبت کرنا", "نفرت کرنا", "لطف اٹھانا", "ترجیح دینا", "قبول کرنا",
    "انکار کرنا", "متفق ہونا", "غیر متفق ہونا", "اجازت دینا", "منع کرنا", "اجازت دینا", "ممانعت کرنا", "درخواست کرنا", "حکم دینا", "حکم دینا",
    "تجویز کرنا", "تجویز کرنا", "مشورہ دینا", "خبردار کرنا", "دھمکی دینا", "وعدہ کرنا", "معذرت کرنا", "معاف کرنا", "شکریہ کہنا", "مبارکباد دینا",
    "جشن منانا", "شرکت کرنا", "حصہ لینا", "شامل ہونا", "چھوڑنا", "پہنچنا", "روانہ ہونا", "داخل ہونا", "باہر نکلنا", "پیچھے چلنا",
    "قیادت کرنا", "رہنمائی کرنا", "مدد کرنا", "مدد کرنا", "سپورٹ کرنا", "مخالفت کرنا", "مزاحمت کرنا", "لڑنا", "دفاع کرنا", "حملہ کرنا",
    "حفاظت کرنا", "پہرا دینا", "چھپانا", "دکھانا", "نمائش کرنا", "ظاہر کرنا", "چھپانا", "وضاحت کرنا", "بیان کرنا", "بتانا",
    "پوچھنا", "جواب دینا", "جواب دینا", "جواب دینا", "بات چیت کرنا", "بحث کرنا", "مباحثہ کرنا", "بحث کرنا", "قائل کرنا", "راضی کرنا",
    "اثر انداز ہونا", "کنٹرول کرنا", "انتظام کرنا", "منظم کرنا", "منصوبہ بنانا", "تیار کرنا", "عمل کرنا", "لاگو کرنا", "حاصل کرنا", "کامیاب ہونا",
    "ناکام ہونا", "بہتر بنانا", "بدتر کرنا", "ترقی", "تنزل", "آگے بڑھنا", "پیچھے ہٹنا", "آگے", "پیچھے", "پار",
    "کے ذریعے", "ارد گرد", "کے بارے میں", "نیچے", "اوپر", "درمیان", "میں سے", "کے ساتھ", "پاس", "سامنے",
    "پیچھے", "اوپر", "نیچے", "پر", "میں", "پر", "سے", "تک", "کے ساتھ", "بغیر",
    "کے لیے", "کا", "کے ذریعے", "جیسا", "سے زیادہ", "سے", "میں", "پر", "سے باہر", "کی طرف",
    "کے خلاف", "پہلے", "بعد", "دوران", "جب تک", "جب سے", "جبکہ", "اگرچہ", "اگرچہ", "اگرچہ",
    "جب تک نہیں", "بشرطیکہ", "تاکہ", "کے لیے", "کے باوجود", "اس کے باوجود", "کے بجائے", "کی وجہ سے", "کی وجہ سے", "کا شکریہ",
    "کے مطابق", "کی جانب سے", "کے علاوہ", "کے علاوہ", "بشمول", "بشمول", "متعلق", "کے بارے میں", "کے بارے میں", "کے بارے میں",
    "جمع", "منفی", "ضرب", "تقسیم", "برابر", "بڑا", "چھوٹا", "فیصد", "نمبر", "مقدار",
    "مقدار", "پیمانہ", "وزن", "لمبائی", "چوڑائی", "اونچائی", "گہرائی", "رقبہ", "حجم", "رفتار",
    "درجہ حرارت", "دباؤ", "توانائی", "طاقت", "قوت", "روشنی (روشن)", "آواز", "شور", "خاموشی", "ارتعاش",
    "لہر", "ذرات", "عنصر", "مرکب", "مخلوط", "حل", "گیس", "مائع", "ٹھوس", "پلازما",
    "ایٹم", "مالیکیول", "سیل", "ٹشو", "عضو", "نظام", "جاندار", "نسل", "آبادی", "برادری",
    "ماحولیاتی نظام", "ماحول", "آب و ہوا", "موسم", "موسم", "بہار", "گرمی", "خزاں", "سردی", "بارش",
    "برف", "ہوا", "بادل", "دھند", "سورج", "چاند", "ستارہ", "سیارہ", "کہکشاں", "کائنات",
    "خلا", "وقت", "جہت", "کشش ثقل", "مقناطیسیت", "بجلی", "گرمی", "سردی", "روشنی (سپیکٹرم)", "آواز (فریکوئنسی)",
    "رنگ", "شکل", "سائز", "ساخت", "نمونہ", "شکل", "ساخت", "فعالیت", "مقصد", "وجہ",
    "وجہ", "اثر", "نتیجہ", "نتیجہ", "ماخذ", "اصل", "منزل", "سفر", "راستہ", "راستہ",
    "سمت", "مقام", "پوزیشن", "جگہ", "نقطہ", "لائن", "مڑ", "زاویہ", "دائرہ", "مربع",
    "تکون", "مستطیل", "بیضوی", "گولہ", "مکعب", "سلنڈر", "مخروط", "اہرام", "کنڈل", "ہیلکس",
    "نیٹ ورک", "نظام", "عمل", "طریقہ کار", "طریقہ", "تکنیک", "حکمت عملی", "طریقہ", "منصوبہ", "منصوبہ",
    "پروگرام", "ایپلی کیشن", "سافٹ ویئر", "ہارڈ ویئر", "ڈیٹا", "معلومات", "علم", "حکمت", "دانش", "تخلیقی صلاحیت",
    "تخیل", "یادداشت", "سوچ", "جذبات", "احساس", "حس", "ادراک", "شعور", "ذہن", "روح",
    "روح", "جسم", "صحت", "بیماری", "درد", "مسرت", "آرام", "تکلیف", "بھوک", "پیاس",
    "تھکاوٹ", "توانائی", "طاقت", "کمزوری", "توازن", "عدم توازن", "ہم آہنگی", "تصادم", "ترتیب", "افراتفری",
    "انصاف", "ناانصافی", "صحیح", "غلط", "نیکی", "برائی", "نیکی", "برائی", "اخلاقی", "اخلاقی",
    "قانونی", "غیر قانونی", "قانون", "اصول", "ضابطہ", "اصول", "قدر", "عقیدہ", "ایمان", "مذہب",
    "روحانیت", "ثقافت", "روایت", "رواج", "رسم", "تقریب", "جشن", "تہوار", "چھٹی", "تقریب",
    "ملاقات", "تقرری", "شیڈول", "ڈیڈ لائن", "ٹاسک", "پروجیکٹ", "مقصد", "مقصد", "ہدف", "مقصد",
    "معنی", "اہمیت", "اہمیت", "قدر", "قیمت", "قیمت", "لاگت", "بجٹ", "مالیات", "معیشت",
    "کاروبار", "تجارت", "تجارت", "صنعت", "زراعت", "ٹیکنالوجی", "سائنس", "تحقیق", "تعلیم", "سیکھنا",
    "سکھانا", "تربیت", "ترقی", "نمو", "پیش رفت", "اختراع", "دریافت", "ایجاد", "تلاش", "مہم جوئی",
    "سفر", "سفر", "چھٹیاں", "چھٹی", "فارغ وقت", "مشغلہ", "کھیل", "گیم", "آرٹ", "موسیقی",
    "رقص", "تھیٹر", "سنیما", "ٹیلی ویژن", "ریڈیو", "انٹرنیٹ", "ویب سائٹ", "ای میل", "پیغام", "کال",
    "فون", "کمپیوٹر", "لیپ ٹاپ", "ٹیبلٹ", "اسمارٹ فون", "کیمرہ", "مائکروفون", "اسپیکر", "ہیڈ فون", "پرنٹر",
    "اسکینر", "کی بورڈ", "ماؤس", "اسکرین", "مانیٹر", "ڈسپلے", "نیٹ ورک", "کنکشن", "وائرلیس", "بلوٹوتھ",
    "کیبل", "پلگ", "ساکٹ", "بیٹری", "چارجر", "پاور", "بجلی", "روشنی", "اندھیرا", "سایہ",
    "عکاسی", "آئینہ", "لینس", "گلاس", "پلاسٹک", "دھات", "لکڑی", "پتھر", "کنکریٹ", "اینٹ",
    "فیبرک", "چمڑا", "کاغذ", "سیاہی", "پینٹ", "برش", "پنسل", "ربڑ", "رولر", "قینچی",
    "گلو", "ٹیپ", "کیل", "پیچ", "ہتھوڑا", "رینچ", "سکریو ڈرایور", "ڈرل", "آری", "کلہاڑی",
    "چاقو", "کانٹا", "چمچ", "پلیٹ", "پیالہ", "کپ", "گلاس", "بوتل", "ڈبہ", "مرتبان",
    "بیگ", "ڈبہ", "کنٹینر", "ٹوکری", "شیلف", "دراز", "کابینہ", "کلوفٹ", "الماری", "ہینگر",
    "کپڑے", "قمیض", "ٹی شرٹ", "جیکٹ", "کوٹ", "سویٹر", "پینٹ", "جینز", "شارٹس", "اسکرٹ",
    "لباس", "جرابیں", "جوتے", "بوٹ", "سینڈل", "ٹوپی", "کیپ", "دستانے", "اسکارف", "بیلٹ",
    "ٹائی", "زیورات", "انگوٹھی", "ہار", "کڑا", "بالی", "گھڑی", "عینک", "دھوپ کا چشمہ", "چھتری",
    "چابی", "تالہ", "پرس", "پرس", "بیک بیگ", "سوٹ کیس", "سامان", "ٹکٹ", "پاسپورٹ", "نقشہ",
    "کمپاس", "گلوب", "جھنڈا", "ترانہ", "علامت", "نشان", "لوگو", "برانڈ", "کمپنی", "کارپوریشن",
    "تنظیم", "ادارہ", "حکومت", "سیاست", "قانون", "انصاف", "جرم", "سزا", "جیل", "عدالت",
    "جج", "وکیل", "پولیس", "فوجی", "فوج", "بحریہ", "فضائیہ", "فوجی", "جنگ", "امن",
    "معاہدہ", "معاہدہ", "معاہدہ", "وعدہ", "حلف", "عہد", "عزم", "ذمہ داری", "فرض", "عزم",
    "حق", "استحقاق", "آزادی", "آزادی", "مساوات", "انصاف", "انصاف پسندی", "ایمانداری", "سالمیت", "اعتماد",
    "وفاداری", "احترام", "مہربانی", "سخاوت", "رحمدلی", "ہمدردی", "صبر", "برداشت", "ہمت", "بہادری",
    "طاقت", "لچک", "عزم", "استقامت", "عزم", "تحریک", "الہام", "تخلیقی صلاحیت", "اختراع", "دریافت",
    "تحقیق", "تجربہ", "نظریہ", "مفروضہ", "نتیجہ", "ثبوت", "حقیقت", "ڈیٹا", "تجزیہ", "ترکیب",
    "خلاصہ", "ٹھوس", "تصور", "خیال", "سوچ", "رائے", "عقیدہ", "نقطہ نظر", "نقطہ نظر", "نقطہ نظر",
    "فرض", "قیاس", "استدلال", "تخفیف", "استدلال", "منطق", "منطق", "بحث", "مباحثہ", "بحث",
    "گفتگو", "مکالمہ", "تقریر", "پیشکش", "لیکچر", "سیمینار", "ورکشاپ", "کانفرنس", "ملاقات", "انٹرویو",
    "سروے", "سوالنامہ", "رپورٹ", "دستاویز", "فائل", "فولڈر", "کابینہ", "شیلف", "ڈیسک", "کرسی",
    "میز", "لیمپ", "گھڑی", "کیلنڈر", "کتاب", "میگزین", "اخبار", "خط", "لفافہ", "ٹکٹ",
    "پوسٹ کارڈ", "گریٹنگ کارڈ", "دعوت نامہ", "ٹکٹ", "رسید", "انوائس", "بل", "معاہدہ", "فارم", "درخواست",
    "ریزومے", "کریکولم وٹائی", "سرٹیفکیٹ", "ڈپلومہ", "ڈگری", "ایوارڈ", "تمغہ", "ٹرافی", "انعام", "تحفہ",
    "تحفہ", "یادگار", "یادگار", "یادگاری", "مجموعہ", "مشغلہ", "گیم", "پہیلی", "کھلونا", "گڑیا",
    "ایکشن فگر", "بورڈ گیم", "کارڈ گیم", "ویڈیو گیم", "کنسول", "کنٹرولر", "جوائے اسٹک", "اسکرین", "مانیٹر", "ڈسپلے",
    "اسپیکر", "ہیڈ فون", "مائکروفون", "کیمرہ", "ویب کیم", "پرنٹر", "اسکینر", "کی بورڈ", "ماؤس", "یو ایس بی ڈرائیو",
    "ہارڈ ڈرائیو", "سالڈ اسٹیٹ ڈرائیو", "میموری کارڈ", "راؤٹر", "موڈیم", "سرور", "نیٹ ورک", "انٹرنیٹ", "ویب سائٹ", "بلاگ",
    "فورم", "سوشل میڈیا", "ای میل", "چیٹ", "پیغام", "کال", "ویڈیو کال", "کانفرنس کال", "وائس میل", "ٹیکسٹ میسج",
    "نوٹیفکیشن", "الرٹ", "وارننگ", "ایرر", "بگ", "گلچ", "کریش", "دوبارہ شروع کریں", "اپ ڈیٹ", "اپ گریڈ",
    "انسٹال کریں", "ان انسٹال کریں", "ڈاؤن لوڈ کریں", "اپ لوڈ کریں", "محفوظ کریں", "کھولیں", "بند کریں", "کاپی کریں", "پیسٹ کریں", "کاٹیں",
    "حذف کریں", "کالعدم کریں", "دوبارہ کریں", "پرنٹ کریں", "اسکین کریں", "تلاش کریں", "تلاش کریں", "بدلیں", "منتخب کریں", "غیر منتخب کریں",
    "کلک کریں", "ڈبل کلک کریں", "دایاں کلک کریں", "گھسیٹیں", "چھوڑ دیں", "سکرول کریں", "زوم ان کریں", "زوم آؤٹ کریں", "زیادہ سے زیادہ کریں", "چھوٹا کریں",
    "بحال کریں", "ریفریش کریں", "لوڈ کریں", "کے طور پر محفوظ کریں", "نیا فولڈر", "نام تبدیل کریں", "پراپرٹیز", "سیٹنگز", "آپشنز", "ترجیحات",
    "مدد", "کے بارے میں", "باہر نکلیں", "چھوڑیں"
]
# Generate English images
for i, txt in enumerate(english_samples):
    generate_text_image(txt, english_font, f"dataset/english/eng_{i}.png")

# Generate Urdu images
for i, txt in enumerate(urdu_samples):
    generate_text_image(txt, urdu_font, f"dataset/urdu/urdu_{i}.png")
